### ISSUE TITLE
Add: Centos Installation

### ISSUE THREAD

**Issue by t-book** [GeoNode/documentation#1]
https://docs.geonode.org/en/master/install/core/index.html#centos-7-0

**Comment by t-book** [comment]
@francbartoli @afabiani @gannebamm @giohappy 

Since we already fight to finish docs I would suggest either remove centos installation or just suggest using docker in this case. This as I do not see anybody available going to the centos install. Your're +1/-1 is welcome.

**Comment by francbartoli** [comment]
+1 , we could recover it from previous docs at our convenience

**Comment by gannebamm** [comment]
+1

**Comment by t-book** [comment]
done by @afabiani closing here.
