### ISSUE TITLE
Update and review documentation about the setup of GeoNode vanilla with Docker for master

### ISSUE THREAD

**Issue by giohappy** [GeoNode/documentation#236]
Documentation [here](https://docs.geonode.org/en/master/install/advanced/core/index.html#deploy-a-vanilla-geonode-3-2-0-with-docker) is outdated.

It must be updated as done for https://github.com/GeoNode/documentation/issues/238

Among other things it's referencing 3.2 and advising to use a docker-compose override instead of .env file

**Comment by jkariukidev** [comment]
Updated as requested and review requested at #241
