### ISSUE TITLE
Update and review GeoNode Project section for master

### ISSUE THREAD

**Issue by giohappy** [GeoNode/documentation#238]
- review the steps, if they're still valid or need to be updated
- update the referenced versions of GeoNode and, in case, of any dependency
- update to Ubuntu 20.04

https://docs.geonode.org/en/master/install/advanced/project/index.html#

**Comment by jkariukidev** [comment]
Made recommended changes with ref #239

**Comment by giohappy** [comment]
@jkariukidev the PR has been merged by @afabiani but there are still parts that must be updated, e.g. all the references to branch 3.2.x.
Please complete the update and send a new PR.

**Comment by jkariukidev** [comment]
Just a clarification. It needs to refer to `3.3.x`

**Comment by giohappy** [comment]
>Just a clarification. It needs to refer to 3.3.x

@joebocop no it needs to refer to `master`. 
During the next weeks, we will have to fork a new `4.0` branch from `master` when the official release of GeoNode 4.0 will happen.
