### ISSUE TITLE
Create section with API usage examples

### ISSUE THREAD

**Issue by giohappy** [GeoNode/documentation#246]
This guide should describe:

 - Authentication
   - Basic Auth
   - Bearer token / apikey parameter (explaining how to obtain the token from Django admin or` /api/o/v4/userinfo`)
 - Resource listing and filtering
 - Update a resource
 - Upload a dataset (ask @mattiagiupponi to give a help on this)
 - Upload a document
 - Download a resource (navigating the download links inside the resource response body)
 - Delete a resource
 - Get the list of users and groups
 - Manage permissions

Bonus: create a PostMan collection with examples for master demo (with a demo user)

**Comment by gannebamm** [comment]
The auth section lacks how to optain the bearer token
> Bearer token / apikey parameter (explaining how to obtain the token from Django admin or /api/o/v4/userinfo)

Not sure if it missing in the docs or missing as functionality in the api 
> Upload a document

Is not part of the PR

**Comment by gannebamm** [comment]
Found the doc upload section:
> At the moment documents can’t be uploaded through the API. This will probably change in the future.

OK, that's a pity. It is the api than

**Comment by giohappy** [comment]
@gannebamm FYI a simple implementation of document upload via API is now available. Example in the doc is still missing though https://github.com/GeoNode/documentation/issues/266
