### ISSUE TITLE
Master docs show wrong Version

### ISSUE THREAD

**Issue by t-book** [GeoNode/documentation#258]
The Browser tilte of docs / master branch show 3.2.1 Version. 

  <title>Accessing the panel &mdash; GeoNode 3.2.1 documentation</title>

It should be 4.0.1

**Comment by giohappy** [comment]
Fixed in https://github.com/GeoNode/documentation/commit/ed1537cdd26a24cefb22cb34ee2ba2c2f6a594a4 and https://github.com/GeoNode/documentation/commit/0a9fea29179ca37b7175962eb0952efedb1aec86
