### ISSUE TITLE
Review the status of the User manual

### ISSUE THREAD

**Issue by giohappy** [GeoNode/documentation#275]
Do a review of the [User manual](https://docs.geonode.org/en/master/usage/index.html) and report here

- outdated information
- missing features

**Comment by ElenaGallo** [comment]
@giohappy I have reported in [this sheet](https://docs.google.com/spreadsheets/d/1Oae-zt8dh1k6jLMABcQlG-yI9nvk33CwtNd1a72Hvqo/edit#gid=0) all the things that need to be updated or added to the manual.
