### ISSUE TITLE
Full GeoNode Backup & Restore: link to "GeoServer Extension" unreachable

### ISSUE THREAD

**Issue by danjde** [GeoNode/documentation#58]
Hi Devs, 
I'm wondering how fair perform backup data, and reading the specific documentation I saw that link to "GeoServer Extension" page is unreachable: http://build.geonode.org/geoserver/latest/

thanks

**Comment by t-book** [comment]
Hi. Thanks for catching this ! As far as I know geosolutions is currently kindly sponsoring the server which now is https://build.geo-solutions.it/geonode/geoserver

@afabiani if I‘m right we could either fix the url in docs or update the record of the subdomain build.geonode .org    I could take care for both solutions.

**Comment by danjde** [comment]
Anyway, from what i saw, all GeoServer Extension are present on geoserver-2.17.2.war, and this could be specified, for clarity ;-)


Thanks

**Comment by t-book** [comment]
I see than it looks this issue is more about a 404.
